{
 "title": "PW Chat Api Service Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   { "name": "datasource", "query": "prometheus" },
   { "name": "namespace", "query": "microservices" },
   { "name": "service", "query": "pw-chat-api-service" },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_info{namespace=\"$namespace\", pod=~\"^$service.*\"}, pod)"
    }
   },
   {
    "name": "error_code_regex",
    "query": "Yes : [123][0-9]{2}, No : [012346789]{3}"
   },
   {
    "name": "interval",
    "query": "auto : $__interval, 30s, 1m,5m,10m,1h,2h,6h,8h,12h,1d"
   }
  ]
 },
 "panels": [
  {
   "title": "PW Chat Api Service Dashboard",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "sum(irate(response_total{deployment=\"pw-chat-api-service\",namespace=\"microservices\"}[5m])) by (deployment)"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=~\"$pod\", direction=\"inbound\", route_name!=\"probe\"}[$interval])) by (le))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=~\"$pod\", direction=\"inbound\", route_name!=\"probe\"}[$interval])) by (le))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", pod=~\"$pod\", direction=\"inbound\", route_name!=\"probe\"}[$interval])) by (le))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Error Codes",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 14, "x": 0, "y": 7 },
     "targets": [
      {
       "expr": "sum(irate(response_total{deployment=\"$service\",namespace=\"microservices\",status_code!=\"2.*\"}[5m])) by (deployment, status_code)"
      }
     ]
    },
    {
     "title": "Replicas Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 10, "x": 14, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(kube_deployment_status_replicas_available{deployment=\"$service\",namespace=\"$namespace\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "CPU Core Usage - Application",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod=~\"^$service.*$\",namespace=\"$namespace\", container!=\"POD\", cpu=\"total\"}[1m])) by (pod)"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"^$service.*$\", unit=\"core\"}) / (kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Request $service"
      }
     ]
    },
    {
     "title": "Memory Usage - Application",
     "type": "graph",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes", "label": "Memory" }
     ],
     "targets": [
      {
       "expr": "container_memory_usage_bytes{image!=\"\", pod=~\"^$service.*\",  namespace=\"$namespace\"}"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"^$service.*$\", unit=\"byte\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Core Requests"
      }
     ]
    },
    {
     "title": "Memory Request and Memory Limits",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"^$service.*$\", unit=\"byte\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Limits $service "
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"^$service.*$\", unit=\"byte\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Requests $service"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"^$service.*$\", container=\"linkerd-proxy\", unit=\"byte\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Requests linkerd-proxy"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"^$service.*$\", container=\"linkerd-proxy\", unit=\"byte\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\", namespace=\"$namespace\"})",
       "legendFormat": "Limits linkerd-proxy"
      }
     ]
    },
    {
     "title": "Open TCP connections",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "sum(irate(tcp_open_connections{deployment=\"$service\",namespace=\"microservices\",status_code!=\"2.*\"}[5m])) by (deployment, status_code)"
      }
     ]
    },
    {
     "title": "CPU Requests and CPU Limits",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"^$service.*$\", unit=\"core\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Limits $service "
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"^$service.*$\", unit=\"core\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Requests $service"
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"^$service.*$\", container=\"linkerd-proxy\", unit=\"core\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Request linkerd-proxy"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"^$service.*$\", container=\"linkerd-proxy\", unit=\"core\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\", namespace=\"$namespace\"})",
       "legendFormat": "Limits linkerd-proxy"
      }
     ]
    },
    {
     "title": "Pods Restarted",
     "type": "graph",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "kube_pod_container_status_restarts_total{namespace=\"microservices\", pod=~\"^$service.*\"}"
      }
     ]
    },
    {
     "title": "CPU Usage %",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 34 },
     "targets": [
      {
       "expr": "( sum (rate (container_cpu_usage_seconds_total{image!=\"\", pod=~\"^$service.*$\",namespace=\"$namespace\", container!=\"POD\", cpu=\"total\"}[1m])) / sum(kube_pod_container_resource_requests{namespace=\"$namespace\",pod=~\"^$service.*$\", unit=\"core\"}) ) * 100"
      }
     ]
    },
    {
     "title": "CPU Core Usage - Linkerd Proxy",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 0, "y": 43 },
     "yaxes": [
      { "format": "none", "label": "cores" }
     ],
     "targets": [
      {
       "expr": "sum (rate(container_cpu_usage_seconds_total{image!=\"\", pod=~\"^$service.*$\",namespace=\"$namespace\", container=\"linkerd-proxy\"}[1m])) by (pod, container)",
       "legendFormat": "  "
      },
      {
       "expr": "sum(kube_pod_container_resource_requests{namespace=\"$namespace\", pod=~\"^$service.*$\", container=\"linkerd-proxy\", unit=\"core\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\",namespace=\"$namespace\"})",
       "legendFormat": "Core Request"
      },
      {
       "expr": "sum(kube_pod_container_resource_limits{namespace=\"$namespace\", pod=~\"^$service.*$\", container=\"linkerd-proxy\", unit=\"core\"}) / sum(kube_deployment_status_replicas{deployment=~\"^$service\", namespace=\"$namespace\"})",
       "legendFormat": "Core Limit"
      }
     ]
    },
    {
     "title": "CPU Throttling",
     "type": "graph",
     "gridPos": { "h": 10, "w": 12, "x": 12, "y": 43 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(increase(container_cpu_cfs_throttled_periods_total{namespace=\"$namespace\", pod=~\"$service.*\", container!=\"POD\"}[1m])) by (pod) /sum(increase(container_cpu_cfs_periods_total{namespace=\"$namespace\", pod=~\"$service.*\", container!=\"POD\"}[1m])) by (pod) * 100"
      }
     ]
    },
    {
     "title": "SUCCESS RATE",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 0, "y": 53 },
     "yaxes": [
      { "format": "percentunit" }
     ],
     "targets": [
      {
       "expr": "sum(irate(response_total{classification=\"success\", namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (dst_service) / sum(irate(response_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (dst_service)",
       "legendFormat": "svc/"
      }
     ]
    },
    {
     "title": "REQUEST RATE",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 8, "y": 53 },
     "yaxes": [
      { "format": "rps" }
     ],
     "targets": [
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\", tls=\"true\"}[$__rate_interval])) by (dst_service)",
       "legendFormat": "🔒svc/"
      },
      {
       "expr": "sum(irate(request_total{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\", tls!=\"true\"}[$__rate_interval])) by (dst_service)",
       "legendFormat": "svc/"
      }
     ]
    },
    {
     "title": "LATENCY",
     "type": "graph",
     "gridPos": { "h": 10, "w": 8, "x": 16, "y": 53 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.5, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_service))",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(0.90, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_service))",
       "legendFormat": "p90"
      },
      {
       "expr": "histogram_quantile(0.95, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_service))",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(0.99, sum(irate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_service))",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Outbound - P90 LATENCY",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 0, "y": 63 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.90, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_service, deployment))",
       "legendFormat": "P90 po/"
      }
     ]
    },
    {
     "title": "Outbound - P95 LATENCY",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 8, "y": 63 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.95, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_service, deployment))",
       "legendFormat": "P95 deploy/"
      }
     ]
    },
    {
     "title": "Outbound - P99 LATENCY",
     "type": "graph",
     "gridPos": { "h": 13, "w": 8, "x": 16, "y": 63 },
     "yaxes": [
      { "format": "ms" }
     ],
     "targets": [
      {
       "expr": "histogram_quantile(0.99, sum(rate(response_latency_ms_bucket{namespace=\"$namespace\", dst_service=\"$service\", direction=\"outbound\"}[$__rate_interval])) by (le, dst_service, deployment))",
       "legendFormat": "P99 deploy/"
      }
     ]
    }
   ]
  },
  { "title": "Redis", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Memory Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-001" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-002" },
     "metricName": "DatabaseMemoryUsagePercentage",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "CPU Usage (%)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-001" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-002" },
     "metricName": "CPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Engine CPU usage ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-001" },
     "metricName": "EngineCPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-002" },
     "metricName": "EngineCPUUtilization",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "cache hit rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-001" },
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    },
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-001" },
     "metricName": "CacheHitRate",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Total current connection count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "targets": [
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-001" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    },
    {
     "dimensions": { "CacheClusterId": "k8s-redis-prod-002" },
     "metricName": "CurrConnections",
     "namespace": "AWS/ElastiCache",
     "queryMode": "Metrics",
     "region": "default",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Mongodb",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "panels": [
    {
     "title": "Disk Read  IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(hardware_disk_metrics_read_count{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}[$__range])) by (instance)"
      },
      {
       "expr": "sum(rate(hardware_disk_metrics_read_count{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}[$__range])) by (instance)"
      },
      {
       "expr": "sum(rate(hardware_disk_metrics_read_count{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}[$__range])) by (instance)"
      }
     ]
    },
    {
     "title": "Disk Write IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 3 },
     "targets": [
      {
       "expr": "sum(rate(hardware_disk_metrics_write_count{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}[$__range])) by (instance)"
      },
      {
       "expr": "sum(rate(hardware_disk_metrics_write_count{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}[$__range])) by (instance)"
      },
      {
       "expr": "sum(rate(hardware_disk_metrics_write_count{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}[$__range])) by (instance)"
      }
     ]
    },
    {
     "title": "Mongo_ops_command",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(mongodb_opcounters_command{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}) by (instance)"
      },
      {
       "expr": "sum(mongodb_opcounters_command{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}) by (instance)"
      },
      {
       "expr": "sum(mongodb_opcounters_command{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}) by (instance)"
      }
     ]
    },
    {
     "title": "Mongo_total_query",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 11 },
     "targets": [
      {
       "expr": "sum(mongodb_opcounters_query{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}) by (instance)"
      },
      {
       "expr": "sum(mongodb_opcounters_query{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}) by (instance)"
      },
      {
       "expr": "sum(mongodb_opcounters_query{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}) by (instance)"
      }
     ]
    },
    {
     "title": "Disk Utilization (%)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "targets": [
      {
       "expr": "sum(hardware_disk_metrics_disk_space_used_bytes{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}) by (instance) /sum (hardware_disk_metrics_disk_space_used_bytes{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"} + hardware_disk_metrics_disk_space_free_bytes{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}) by (instance) *100"
      },
      {
       "expr": "sum(hardware_disk_metrics_disk_space_used_bytes{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}) by (instance) /sum (hardware_disk_metrics_disk_space_used_bytes{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"} + hardware_disk_metrics_disk_space_free_bytes{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}) by (instance) *100"
      },
      {
       "expr": "sum(hardware_disk_metrics_disk_space_used_bytes{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}) by (instance) /sum (hardware_disk_metrics_disk_space_used_bytes{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"} + hardware_disk_metrics_disk_space_free_bytes{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}) by (instance) *100"
      }
     ]
    },
    {
     "title": "System Memory Usage (in GB)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "targets": [
      {
       "expr": "(hardware_system_memory_mem_total_kilobytes{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}-hardware_system_memory_mem_free_kilobytes{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"})/(1024*1024) "
      },
      {
       "expr": "(hardware_system_memory_mem_total_kilobytes{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}-hardware_system_memory_mem_free_kilobytes{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"})/(1024*1024) "
      },
      {
       "expr": "(hardware_system_memory_mem_total_kilobytes{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}-hardware_system_memory_mem_free_kilobytes{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"})/(1024*1024) "
      }
     ]
    },
    {
     "title": "CPU's utilisation for I/O-bound operations ( in min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "targets": [
      {
       "expr": "hardware_system_cpu_io_wait_milliseconds{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}/60000"
      },
      {
       "expr": "hardware_system_cpu_io_wait_milliseconds{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}/60000"
      },
      {
       "expr": "hardware_system_cpu_io_wait_milliseconds{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}/60000"
      }
     ]
    },
    {
     "title": "CPU's utilisation for kernel-related operations.( in min)",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "targets": [
      {
       "expr": "hardware_system_cpu_kernel_milliseconds{instance=\"penpencil-production-co-shard-00-00.qeaxj.mongodb.net:27018\"}/60000"
      },
      {
       "expr": "hardware_system_cpu_kernel_milliseconds{instance=\"penpencil-production-co-shard-00-01.qeaxj.mongodb.net:27018\"}/60000"
      },
      {
       "expr": "hardware_system_cpu_kernel_milliseconds{instance=\"penpencil-production-co-shard-00-02.qeaxj.mongodb.net:27018\"}/60000"
      }
     ]
    }
   ]
  }
 ]
}