{
 "title": "fastag-uat-kafka-ankita",
 "description": "Kafka resource usage and throughput",
 "tags": [
  "kafka",
  "service"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" },
   {
    "name": "job",
    "label": "job",
    "query": {
     "query": "label_values(kafka_brokers, job)"
    }
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "label_values(kafka_brokers{job=\"$job\"}, instance)"
    }
   },
   {
    "name": "topic",
    "label": "Topic",
    "query": {
     "query": "label_values(kafka_topic_partition_current_offset{instance=~\"$instance:.*\"}, topic)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total Ongoing Alerts for selected service",
   "type": "stat",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "count(ALERTS{service=~\"$service\"})"
    },
    {}
   ]
  },
  {
   "title": "Alerts associated with selected service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "count by (alertname,priority,Priority,severity)(group(ALERTS{alertstate=\"firing\",service=~\"$service\"}) by (alertname,instance,priority,Priority,severity))",
     "legendFormat": "[Total] {{alertname}} {{priority}} {{Priority}} {{severity}}"
    },
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "expr": "count(ALERTS{alertstate=\"firing\",service=~\"$service\"}) by (alertname,instance)",
     "legendFormat": "[Individual] {{alertname}} ~ {{instance}}",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  { "title": "Kafka Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 } },
  {
   "title": "Lag by  Consumer Group",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_consumergroup_lag{instance=~\"$instance:.*\",topic=~\"$topic\"}) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} | {{topic}}"
    }
   ]
  },
  {
   "title": "Message in per second",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(rate(kafka_topic_partition_current_offset{instance=~\"$instance:.*\", topic=~\"$topic\"}[1m])) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message in per minute",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_topic_partition_current_offset{instance=~'$instance:.*', topic=~\"$topic\",job=~\"$job\"}[5m])/5) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  },
  {
   "title": "Message consume per minute",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(delta(kafka_consumergroup_current_offset{instance=~'$instance:.*',topic=~\"$topic\",job=~\"$job\"}[5m])/5) by (consumergroup, topic)",
     "legendFormat": "{{consumergroup}} (topic: {{topic}})"
    }
   ]
  },
  {
   "title": "Kafka Broker Count",
   "type": "stat",
   "gridPos": { "h": 9, "w": 10, "x": 0, "y": 58 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_brokers{instance=~\"$instance:.*\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Partition Leader",
   "type": "table-old",
   "gridPos": { "h": 9, "w": 14, "x": 10, "y": 58 },
   "targets": [
    {
     "expr": "kafka_topic_partition_leader{instance=~\"$instance:.*\",topic=~\"$topic\",job=~\"$job\"}"
    }
   ]
  },
  {
   "title": "Partitions per Topic",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_topic_partitions{job=\"fastag-acquirer-uat\"}) by (topic)",
     "legendFormat": "{{topic}}"
    }
   ]
  }
 ]
}