#!/bin/bash
IP=$(ip addr show|grep inet|egrep '172.23|10.100.' |awk -F " " '{print $2}'|awk -F "/" '{print $1}')
NUM=$(echo $IP | awk -F'.' '{print $(NF-1)$NF}')
hostnamectl set-hostname messagebrokerkafka-fastag-v1-$NUM
cat<<EOF > /etc/hosts
127.0.0.1   localhost localhost.localdomain localhost4 localhost4.localdomain4
::1         localhost localhost.localdomain localhost6 localhost6.localdomain6
$IP $(hostname).fastagprod.awsmum1a.paytmpb.io $(hostname)
EOF
## resolv conf setup
cat<<EOF > /etc/resolv.conf
; generated by /usr/sbin/dhclient-script
search ap-south-1.compute.internal fastagprod.awsmum1b.paytmpb.io fastagprod.awsmum1a.paytmpb.io
nameserver 172.23.176.2
options timeout:3
options attempts:2
EOF
cat<<EOF > /etc/salt/grains
organization: paytmbank
businessunit: banktech
component: fastag
subcomponent: tomcat
role: netc-gratification
servicetype: database
environment: fastagprod
environmentversion: v1
infraversion: v1
datacenter: ap-south-1
rack: ap-south-1a
EOF
## register to salt master
echo "master: 172.23.138.10" > /etc/salt/minion
systemctl restart salt-minion
## running
salt-call state.sls useraccess -ldebug